title: hexo
subtitle: "x xxxx, xxxxxx & xxxxxxx xxxx xxxxxxxxx xxxxxxx xx xxxxxxx."
description: "xxxx xx x xxxx, xxxxxx & xxxxxx xxxx xxxxxxxx xxxxxxx xx xxxxxxx."
author: 武汉飞乐互动科技有限公司
language: en
timezone: UTC

url: https://www.castpeer.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

livere:
  enable: true
  livere_uid: MTAyMC81ODA5OS8zNDU2Mg==
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: hexojs
github: hexojs/hexo
